using Microsoft.EntityFrameworkCore;
using NutritionTracker.Domain.Foods;
using NutritionTracker.Domain.Profiles;
using NutritionTracker.Infrastructure.Persistence;

namespace NutritionTracker.Api.Nutrition;

public sealed record RecipeIngredientRequest(Guid FoodId, decimal Grams, string? Notes);
public sealed record RecipeRequest(string Name, string? Description, string? PreparationNotes, decimal YieldGrams, decimal ServingCount, bool IsSavedTemplate, IReadOnlyList<RecipeIngredientRequest> Ingredients);
public sealed record HabitOperationRequest(decimal? Millilitres, DateTime? RecordedAtUtc, DateTime? StartedAtUtc, DateTime? EndedAtUtc, string? Type, TimeOnly? LocalTime, string? Timezone, bool? IsEnabled, string? ClientOperationId);

public static class NutritionExpansionEndpoints
{
    public static IEndpointRouteBuilder MapNutritionExpansionEndpoints(this IEndpointRouteBuilder routes)
    {
        var recipes = routes.MapGroup("/api/recipes"); recipes.MapGet("", ListRecipes); recipes.MapGet("/{id:guid}", GetRecipe); recipes.MapPost("", CreateRecipe); recipes.MapPut("/{id:guid}", UpdateRecipe); recipes.MapDelete("/{id:guid}", DeleteRecipe);
        var preferences = routes.MapGroup("/api/dietary-preferences"); preferences.MapGet("", GetPreferences); preferences.MapPut("", PutPreferences);
        var habits = routes.MapGroup("/api/habits"); habits.MapGet("/summary", Summary); habits.MapPost("/hydration", AddHydration); habits.MapPost("/fasting", AddFasting); habits.MapPut("/reminders/{id:guid}", PutReminder); habits.MapGet("/reminders", GetReminders);
        return routes;
    }
    private static string User(HttpContext c) => c.Request.Headers.TryGetValue("X-Development-User-Id", out var x) && !string.IsNullOrWhiteSpace(x) ? x.ToString() : throw new BadHttpRequestException("X-Development-User-Id is required.", 401);
    private static IQueryable<Recipe> Owned(NutritionTrackerDbContext db, string user) => db.Recipes.Include(x => x.Ingredients).ThenInclude(x => x.Food).Where(x => x.UserId == user && x.IsActive);
    private static async Task<IResult> ListRecipes(HttpContext c, NutritionTrackerDbContext db, CancellationToken ct) => Results.Ok(await Owned(db, User(c)).AsNoTracking().OrderBy(x => x.Name).Select(x => View(x)).ToListAsync(ct));
    private static async Task<IResult> GetRecipe(HttpContext c, NutritionTrackerDbContext db, Guid id, CancellationToken ct) => await Owned(db, User(c)).AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, ct) is { } r ? Results.Ok(View(r)) : Results.NotFound();
    private static async Task<IResult> CreateRecipe(HttpContext c, NutritionTrackerDbContext db, RecipeRequest r, CancellationToken ct) { var user = User(c); var recipe = await Apply(new Recipe { UserId = user }, r, db, ct); db.Recipes.Add(recipe); await db.SaveChangesAsync(ct); return Results.Created($"/api/recipes/{recipe.Id}", View(recipe)); }
    private static async Task<IResult> UpdateRecipe(HttpContext c, NutritionTrackerDbContext db, Guid id, RecipeRequest r, CancellationToken ct) { var recipe = await Owned(db, User(c)).SingleOrDefaultAsync(x => x.Id == id, ct); if (recipe is null) return Results.NotFound(); await Apply(recipe, r, db, ct); await db.SaveChangesAsync(ct); return Results.Ok(View(recipe)); }
    private static async Task<IResult> DeleteRecipe(HttpContext c, NutritionTrackerDbContext db, Guid id, CancellationToken ct) { var recipe = await db.Recipes.SingleOrDefaultAsync(x => x.Id == id && x.UserId == User(c), ct); if (recipe is null) return Results.NotFound(); recipe.IsActive = false; await db.SaveChangesAsync(ct); return Results.NoContent(); }
    private static async Task<Recipe> Apply(Recipe recipe, RecipeRequest request, NutritionTrackerDbContext db, CancellationToken ct) { if (string.IsNullOrWhiteSpace(request.Name) || request.Name.Length > 160 || request.YieldGrams <= 0 || request.ServingCount <= 0 || request.Ingredients.Count == 0) throw new BadHttpRequestException("Recipe details are invalid."); var ids = request.Ingredients.Select(x => x.FoodId).Distinct().ToList(); if (ids.Count != request.Ingredients.Count || request.Ingredients.Any(x => x.Grams <= 0) || await db.Foods.CountAsync(x => ids.Contains(x.Id) && x.IsActive, ct) != ids.Count) throw new BadHttpRequestException("Recipe ingredients are invalid."); recipe.Name = request.Name.Trim(); recipe.Description = request.Description?.Trim(); recipe.PreparationNotes = request.PreparationNotes?.Trim(); recipe.YieldGrams = request.YieldGrams; recipe.ServingCount = request.ServingCount; recipe.IsSavedTemplate = request.IsSavedTemplate; recipe.Ingredients.Clear(); foreach (var x in request.Ingredients) recipe.Ingredients.Add(new RecipeIngredient { FoodId = x.FoodId, Grams = x.Grams, Notes = x.Notes?.Trim() }); return recipe; }
    private static object View(Recipe r) { var total = r.Ingredients.Sum(i => i.Grams / 100m * i.Food.CaloriesPer100Grams); return new { r.Id, r.Name, r.Description, r.PreparationNotes, r.YieldGrams, r.ServingCount, r.IsSavedTemplate, CaloriesPerServing = decimal.Round(total / r.ServingCount, 1), Ingredients = r.Ingredients.Select(i => new { i.FoodId, Food = i.Food.DisplayName, i.Grams, i.Notes }) }; }
    private static async Task<IResult> GetPreferences(HttpContext c, NutritionTrackerDbContext db, CancellationToken ct) => Results.Ok(await db.UserDietaryPreferences.Where(x => x.UserId == User(c)).OrderBy(x => x.Code).Select(x => new { x.Code, x.Notes }).ToListAsync(ct));
    private static async Task<IResult> PutPreferences(HttpContext c, NutritionTrackerDbContext db, IReadOnlyList<UserDietaryPreference> values, CancellationToken ct) { var user = User(c); db.UserDietaryPreferences.RemoveRange(db.UserDietaryPreferences.Where(x => x.UserId == user)); db.UserDietaryPreferences.AddRange(values.Where(x => !string.IsNullOrWhiteSpace(x.Code)).DistinctBy(x => x.Code.Trim(), StringComparer.OrdinalIgnoreCase).Select(x => new UserDietaryPreference { UserId = user, Code = x.Code.Trim().ToLowerInvariant(), Notes = x.Notes?.Trim() })); await db.SaveChangesAsync(ct); return await GetPreferences(c, db, ct); }
    private static async Task<IResult> AddHydration(HttpContext c, NutritionTrackerDbContext db, HabitOperationRequest r, CancellationToken ct) { var user = User(c); if (r.Millilitres is not > 0 or > 5000) return Results.BadRequest(); if (!string.IsNullOrWhiteSpace(r.ClientOperationId) && await db.HydrationEntries.AnyAsync(x => x.UserId == user && x.ClientOperationId == r.ClientOperationId, ct)) return Results.Conflict(); var entry = new HydrationEntry { UserId = user, Millilitres = r.Millilitres.Value, RecordedAtUtc = r.RecordedAtUtc?.ToUniversalTime() ?? DateTime.UtcNow, ClientOperationId = r.ClientOperationId }; db.HydrationEntries.Add(entry); await db.SaveChangesAsync(ct); return Results.Created("/api/habits/hydration", entry); }
    private static async Task<IResult> AddFasting(HttpContext c, NutritionTrackerDbContext db, HabitOperationRequest r, CancellationToken ct) { var user = User(c); if (r.StartedAtUtc is null || r.EndedAtUtc <= r.StartedAtUtc) return Results.BadRequest(); var entry = new FastingWindow { UserId = user, StartedAtUtc = r.StartedAtUtc.Value.ToUniversalTime(), EndedAtUtc = r.EndedAtUtc?.ToUniversalTime(), ClientOperationId = r.ClientOperationId }; db.FastingWindows.Add(entry); await db.SaveChangesAsync(ct); return Results.Created("/api/habits/fasting", entry); }
    private static async Task<IResult> GetReminders(HttpContext c, NutritionTrackerDbContext db, CancellationToken ct) => Results.Ok(await db.ReminderPreferences.Where(x => x.UserId == User(c)).OrderBy(x => x.LocalTime).ToListAsync(ct));
    private static async Task<IResult> PutReminder(HttpContext c, NutritionTrackerDbContext db, Guid id, HabitOperationRequest r, CancellationToken ct) { if (string.IsNullOrWhiteSpace(r.Type) || r.LocalTime is null || string.IsNullOrWhiteSpace(r.Timezone)) return Results.BadRequest(); var user = User(c); var item = await db.ReminderPreferences.SingleOrDefaultAsync(x => x.Id == id && x.UserId == user, ct) ?? new ReminderPreference { Id = id, UserId = user }; item.Type = r.Type; item.LocalTime = r.LocalTime.Value; item.Timezone = r.Timezone; item.IsEnabled = r.IsEnabled ?? true; if (item.CreatedAtUtc == default) db.ReminderPreferences.Add(item); await db.SaveChangesAsync(ct); return Results.Ok(item); }
    private static async Task<IResult> Summary(HttpContext c, NutritionTrackerDbContext db, DateOnly? date, CancellationToken ct) { var user = User(c); var day = date ?? DateOnly.FromDateTime(DateTime.UtcNow); var start = day.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc); var end = start.AddDays(1); var water = await db.HydrationEntries.Where(x => x.UserId == user && x.RecordedAtUtc >= start && x.RecordedAtUtc < end).SumAsync(x => (decimal?)x.Millilitres, ct) ?? 0; var meals = await db.Meals.Where(x => x.UserId == user && x.Status == Domain.Meals.MealStatus.Confirmed && x.ConsumedAtUtc >= start && x.ConsumedAtUtc < end).CountAsync(ct); return Results.Ok(new { Date = day, HydrationMillilitres = water, ConfirmedMeals = meals, Disclaimer = "Habit summaries are informational and are not medical advice." }); }
}
