using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NutritionTracker.Domain.Foods;
namespace NutritionTracker.Infrastructure.Persistence.Configurations;

public sealed class FoodConfiguration : IEntityTypeConfiguration<Food>
{
    public void Configure(EntityTypeBuilder<Food> builder)
    {
        builder.ToTable("foods", t => t.HasCheckConstraint("CK_foods_nutrients_nonnegative", "\"CaloriesPer100Grams\" >= 0 AND \"ProteinGramsPer100Grams\" BETWEEN 0 AND 100 AND \"CarbohydrateGramsPer100Grams\" BETWEEN 0 AND 100 AND \"FatGramsPer100Grams\" BETWEEN 0 AND 100 AND \"FibreGramsPer100Grams\" BETWEEN 0 AND 100"));
        builder.HasKey(x => x.Id); builder.Property(x => x.CanonicalName).HasMaxLength(160).IsRequired(); builder.Property(x => x.NormalizedName).HasMaxLength(160).IsRequired(); builder.Property(x => x.DisplayName).HasMaxLength(160).IsRequired(); builder.Property(x => x.Description).HasMaxLength(1000); builder.Property(x => x.DataSource).HasMaxLength(160).IsRequired(); builder.Property(x => x.SourceReference).HasMaxLength(500); builder.Property(x => x.SourceVersion).HasMaxLength(80); builder.Property(x => x.OwnerUserId).HasMaxLength(128); builder.Property(x => x.CaloriesPer100Grams).HasPrecision(9, 3); builder.Property(x => x.ProteinGramsPer100Grams).HasPrecision(9, 3); builder.Property(x => x.CarbohydrateGramsPer100Grams).HasPrecision(9, 3); builder.Property(x => x.FatGramsPer100Grams).HasPrecision(9, 3); builder.Property(x => x.FibreGramsPer100Grams).HasPrecision(9, 3); builder.Property(x => x.SugarGramsPer100Grams).HasPrecision(9, 3); builder.Property(x => x.SodiumMilligramsPer100Grams).HasPrecision(10, 3); builder.Property(x => x.Category).HasConversion<string>().HasMaxLength(32); builder.Property(x => x.Cuisine).HasConversion<string>().HasMaxLength(32); builder.Property(x => x.PreparationMethod).HasConversion<string>().HasMaxLength(32); builder.Property(x => x.FoodState).HasConversion<string>().HasMaxLength(24); builder.HasIndex(x => x.NormalizedName); builder.HasIndex(x => x.Category); builder.HasIndex(x => x.Cuisine); builder.HasIndex(x => x.OwnerUserId); builder.HasIndex(x => x.IsActive); builder.HasIndex(x => x.PendingMealId); builder.HasIndex(x => x.IsVerified);
    }
}
public sealed class FoodAliasConfiguration : IEntityTypeConfiguration<FoodAlias>
{ public void Configure(EntityTypeBuilder<FoodAlias> builder) { builder.ToTable("food_aliases"); builder.HasKey(x => x.Id); builder.Property(x => x.Alias).HasMaxLength(160).IsRequired(); builder.Property(x => x.NormalizedAlias).HasMaxLength(160).IsRequired(); builder.Property(x => x.LanguageCode).HasMaxLength(16); builder.Property(x => x.Region).HasMaxLength(80); builder.Property(x => x.Transliteration).HasMaxLength(160); builder.Property(x => x.AliasType).HasConversion<string>().HasMaxLength(32); builder.HasIndex(x => new { x.FoodId, x.NormalizedAlias }).IsUnique(); builder.HasIndex(x => x.NormalizedAlias); builder.HasOne(x => x.Food).WithMany(x => x.Aliases).HasForeignKey(x => x.FoodId).OnDelete(DeleteBehavior.Cascade); } }
public sealed class ServingUnitConfiguration : IEntityTypeConfiguration<ServingUnit>
{ public void Configure(EntityTypeBuilder<ServingUnit> builder) { builder.ToTable("serving_units"); builder.HasKey(x => x.Id); builder.Property(x => x.Code).HasMaxLength(32).IsRequired(); builder.Property(x => x.DisplayName).HasMaxLength(80).IsRequired(); builder.Property(x => x.Symbol).HasMaxLength(16); builder.Property(x => x.UnitType).HasConversion<string>().HasMaxLength(32); builder.HasIndex(x => x.Code).IsUnique(); } }
public sealed class FoodServingConversionConfiguration : IEntityTypeConfiguration<FoodServingConversion>
{ public void Configure(EntityTypeBuilder<FoodServingConversion> builder) { builder.ToTable("food_serving_conversions", t => t.HasCheckConstraint("CK_food_serving_conversions_positive", "\"Quantity\" > 0 AND \"EquivalentGrams\" > 0")); builder.HasKey(x => x.Id); builder.Property(x => x.Quantity).HasPrecision(9, 3); builder.Property(x => x.EquivalentGrams).HasPrecision(9, 3); builder.Property(x => x.Source).HasMaxLength(160).IsRequired(); builder.Property(x => x.SourceReference).HasMaxLength(500); builder.Property(x => x.Confidence).HasConversion<string>().HasMaxLength(16); builder.HasIndex(x => new { x.FoodId, x.ServingUnitId }).IsUnique().HasFilter("\"IsDefault\" = TRUE"); builder.HasOne(x => x.Food).WithMany(x => x.ServingConversions).HasForeignKey(x => x.FoodId).OnDelete(DeleteBehavior.Cascade); builder.HasOne(x => x.ServingUnit).WithMany(x => x.FoodServingConversions).HasForeignKey(x => x.ServingUnitId).OnDelete(DeleteBehavior.Restrict); } }
