using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NutritionTracker.Domain.Meals;
namespace NutritionTracker.Infrastructure.Persistence.Configurations;

public sealed class MealConfiguration : IEntityTypeConfiguration<Meal>
{
    public void Configure(EntityTypeBuilder<Meal> builder) { var b = builder; b.ToTable("meals"); b.HasKey(x => x.Id); b.Property(x => x.UserId).HasMaxLength(128).IsRequired(); b.Property(x => x.Name).HasMaxLength(160); b.Property(x => x.MealType).HasConversion<string>().HasMaxLength(24); b.Property(x => x.Status).HasConversion<string>().HasMaxLength(32); b.Property(x => x.TotalCalories).HasPrecision(9, 3); b.Property(x => x.TotalProteinGrams).HasPrecision(9, 3); b.Property(x => x.TotalCarbohydrateGrams).HasPrecision(9, 3); b.Property(x => x.TotalFatGrams).HasPrecision(9, 3); b.Property(x => x.TotalFibreGrams).HasPrecision(9, 3); b.Property(x => x.OverallConfidence).HasPrecision(5, 4); b.HasIndex(x => new { x.UserId, x.ConsumedAtUtc }); b.HasIndex(x => x.Status); }
}
public sealed class MealImageConfiguration : IEntityTypeConfiguration<MealImage>
{ public void Configure(EntityTypeBuilder<MealImage> builder) { var b = builder; b.ToTable("meal_images"); b.HasKey(x => x.Id); b.Property(x => x.StorageKey).HasMaxLength(300).IsRequired(); b.Property(x => x.MimeType).HasMaxLength(64).IsRequired(); b.Property(x => x.Sha256Hash).HasMaxLength(64).IsRequired(); b.HasIndex(x => x.MealId); b.HasIndex(x => new { x.MealId, x.Sha256Hash }); b.HasOne(x => x.Meal).WithMany(x => x.Images).HasForeignKey(x => x.MealId).OnDelete(DeleteBehavior.Cascade); } }
public sealed class MealItemConfiguration : IEntityTypeConfiguration<MealItem>
{ public void Configure(EntityTypeBuilder<MealItem> builder) { var b = builder; b.ToTable("meal_items"); b.HasKey(x => x.Id); b.Property(x => x.DetectedName).HasMaxLength(160).IsRequired(); b.Property(x => x.RegionalName).HasMaxLength(160); b.Property(x => x.CanonicalName).HasMaxLength(160); b.Property(x => x.PreparationMethod).HasConversion<string>().HasMaxLength(32); b.Property(x => x.EstimatedServingUnit).HasMaxLength(32); b.Property(x => x.EstimatedQuantity).HasPrecision(9, 3); b.Property(x => x.EstimatedGrams).HasPrecision(9, 3); b.Property(x => x.Calories).HasPrecision(9, 3); b.Property(x => x.ProteinGrams).HasPrecision(9, 3); b.Property(x => x.CarbohydrateGrams).HasPrecision(9, 3); b.Property(x => x.FatGrams).HasPrecision(9, 3); b.Property(x => x.FibreGrams).HasPrecision(9, 3); b.Property(x => x.RecognitionConfidence).HasPrecision(5, 4); b.Property(x => x.PortionConfidence).HasPrecision(5, 4); b.Property(x => x.NutritionMatchConfidence).HasPrecision(5, 4); b.Property(x => x.Warnings).HasMaxLength(1500); b.HasIndex(x => x.MealId); b.HasIndex(x => x.FoodId); b.HasOne(x => x.Meal).WithMany(x => x.Items).HasForeignKey(x => x.MealId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.Food).WithMany().HasForeignKey(x => x.FoodId).OnDelete(DeleteBehavior.SetNull); } }
public sealed class AiAnalysisRunConfiguration : IEntityTypeConfiguration<AiAnalysisRun>
{ public void Configure(EntityTypeBuilder<AiAnalysisRun> builder) { var b = builder; b.ToTable("ai_analysis_runs"); b.HasKey(x => x.Id); b.Property(x => x.UserId).HasMaxLength(128).IsRequired(); b.Property(x => x.Provider).HasMaxLength(64).IsRequired(); b.Property(x => x.Model).HasMaxLength(120); b.Property(x => x.PromptVersion).HasMaxLength(40).IsRequired(); b.Property(x => x.SchemaVersion).HasMaxLength(40).IsRequired(); b.Property(x => x.InputImageHash).HasMaxLength(64).IsRequired(); b.Property(x => x.Status).HasConversion<string>().HasMaxLength(24); b.Property(x => x.ProviderRequestId).HasMaxLength(160); b.Property(x => x.FailureType).HasMaxLength(64); b.Property(x => x.ErrorCode).HasMaxLength(64); b.HasIndex(x => x.MealId); b.HasIndex(x => new { x.UserId, x.InputImageHash }); b.HasOne(x => x.Meal).WithMany(x => x.AnalysisRuns).HasForeignKey(x => x.MealId).OnDelete(DeleteBehavior.Cascade); } }

