using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NutritionTracker.Domain.Foods;
using NutritionTracker.Domain.Profiles;
#pragma warning disable CA1725
namespace NutritionTracker.Infrastructure.Persistence.Configurations;

public sealed class NutrientDefinitionConfiguration : IEntityTypeConfiguration<NutrientDefinition> { public void Configure(EntityTypeBuilder<NutrientDefinition> b) { b.ToTable("nutrient_definitions"); b.HasKey(x => x.Id); b.Property(x => x.Code).HasMaxLength(48).IsRequired(); b.Property(x => x.DisplayName).HasMaxLength(96).IsRequired(); b.Property(x => x.Unit).HasConversion<string>().HasMaxLength(24); b.HasIndex(x => x.Code).IsUnique(); } }
public sealed class FoodNutrientConfiguration : IEntityTypeConfiguration<FoodNutrient> { public void Configure(EntityTypeBuilder<FoodNutrient> b) { b.ToTable("food_nutrients", t => t.HasCheckConstraint("CK_food_nutrients_nonnegative", "\"ValuePer100Grams\" >= 0")); b.HasKey(x => x.Id); b.Property(x => x.ValuePer100Grams).HasPrecision(12, 4); b.Property(x => x.Source).HasMaxLength(160).IsRequired(); b.Property(x => x.SourceReference).HasMaxLength(500); b.Property(x => x.Confidence).HasConversion<string>().HasMaxLength(16); b.HasIndex(x => new { x.FoodId, x.NutrientDefinitionId }).IsUnique(); b.HasOne(x => x.Food).WithMany(x => x.Nutrients).HasForeignKey(x => x.FoodId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.NutrientDefinition).WithMany().HasForeignKey(x => x.NutrientDefinitionId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class FoodTagConfiguration : IEntityTypeConfiguration<FoodTag> { public void Configure(EntityTypeBuilder<FoodTag> b) { b.ToTable("food_tags"); b.HasKey(x => x.Id); b.Property(x => x.Code).HasMaxLength(64).IsRequired(); b.Property(x => x.DisplayName).HasMaxLength(96).IsRequired(); b.Property(x => x.Category).HasMaxLength(32).IsRequired(); b.HasIndex(x => x.Code).IsUnique(); } }
public sealed class FoodTagAssignmentConfiguration : IEntityTypeConfiguration<FoodTagAssignment> { public void Configure(EntityTypeBuilder<FoodTagAssignment> b) { b.ToTable("food_tag_assignments"); b.HasKey(x => x.Id); b.HasIndex(x => new { x.FoodId, x.FoodTagId }).IsUnique(); b.HasOne(x => x.Food).WithMany(x => x.TagAssignments).HasForeignKey(x => x.FoodId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.FoodTag).WithMany().HasForeignKey(x => x.FoodTagId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class RecipeConfiguration : IEntityTypeConfiguration<Recipe> { public void Configure(EntityTypeBuilder<Recipe> b) { b.ToTable("recipes", t => t.HasCheckConstraint("CK_recipes_yield", "\"YieldGrams\" > 0 AND \"ServingCount\" > 0")); b.HasKey(x => x.Id); b.Property(x => x.UserId).HasMaxLength(128).IsRequired(); b.Property(x => x.Name).HasMaxLength(160).IsRequired(); b.Property(x => x.Description).HasMaxLength(1000); b.Property(x => x.PreparationNotes).HasMaxLength(2000); b.Property(x => x.YieldGrams).HasPrecision(10, 3); b.Property(x => x.ServingCount).HasPrecision(8, 2); b.HasIndex(x => new { x.UserId, x.Name }); } }
public sealed class RecipeIngredientConfiguration : IEntityTypeConfiguration<RecipeIngredient> { public void Configure(EntityTypeBuilder<RecipeIngredient> b) { b.ToTable("recipe_ingredients", t => t.HasCheckConstraint("CK_recipe_ingredients_grams", "\"Grams\" > 0")); b.HasKey(x => x.Id); b.Property(x => x.Grams).HasPrecision(10, 3); b.Property(x => x.Notes).HasMaxLength(500); b.HasIndex(x => new { x.RecipeId, x.FoodId }); b.HasOne(x => x.Recipe).WithMany(x => x.Ingredients).HasForeignKey(x => x.RecipeId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.Food).WithMany().HasForeignKey(x => x.FoodId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class UserDietaryPreferenceConfiguration : IEntityTypeConfiguration<UserDietaryPreference> { public void Configure(EntityTypeBuilder<UserDietaryPreference> b) { b.ToTable("user_dietary_preferences"); b.HasKey(x => x.Id); b.Property(x => x.UserId).HasMaxLength(128).IsRequired(); b.Property(x => x.Code).HasMaxLength(64).IsRequired(); b.Property(x => x.Notes).HasMaxLength(500); b.HasIndex(x => new { x.UserId, x.Code }).IsUnique(); } }
public sealed class HydrationEntryConfiguration : IEntityTypeConfiguration<HydrationEntry> { public void Configure(EntityTypeBuilder<HydrationEntry> b) { b.ToTable("hydration_entries", t => t.HasCheckConstraint("CK_hydration_entries_amount", "\"Millilitres\" > 0")); b.HasKey(x => x.Id); b.Property(x => x.Millilitres).HasPrecision(8, 1); b.Property(x => x.UserId).HasMaxLength(128).IsRequired(); b.Property(x => x.ClientOperationId).HasMaxLength(64); b.HasIndex(x => new { x.UserId, x.RecordedAtUtc }); b.HasIndex(x => new { x.UserId, x.ClientOperationId }).IsUnique().HasFilter("\"ClientOperationId\" IS NOT NULL"); } }
public sealed class FastingWindowConfiguration : IEntityTypeConfiguration<FastingWindow> { public void Configure(EntityTypeBuilder<FastingWindow> b) { b.ToTable("fasting_windows"); b.HasKey(x => x.Id); b.Property(x => x.UserId).HasMaxLength(128).IsRequired(); b.Property(x => x.ClientOperationId).HasMaxLength(64); b.HasIndex(x => new { x.UserId, x.StartedAtUtc }); b.HasIndex(x => new { x.UserId, x.ClientOperationId }).IsUnique().HasFilter("\"ClientOperationId\" IS NOT NULL"); } }
public sealed class ReminderPreferenceConfiguration : IEntityTypeConfiguration<ReminderPreference> { public void Configure(EntityTypeBuilder<ReminderPreference> b) { b.ToTable("reminder_preferences"); b.HasKey(x => x.Id); b.Property(x => x.UserId).HasMaxLength(128).IsRequired(); b.Property(x => x.Type).HasMaxLength(32).IsRequired(); b.Property(x => x.Timezone).HasMaxLength(64).IsRequired(); b.Property(x => x.ClientOperationId).HasMaxLength(64); b.HasIndex(x => new { x.UserId, x.Type }); } }
