using Microsoft.EntityFrameworkCore;
using NutritionTracker.Application.Foods;
using NutritionTracker.Application.Meals;
using NutritionTracker.Domain.Foods;
using NutritionTracker.Domain.Meals;
using NutritionTracker.Infrastructure.Persistence;
namespace NutritionTracker.Infrastructure.Meals;

public sealed class MealManagementService(NutritionTrackerDbContext db, IFoodNutritionCalculator nutrition) : IMealManagementService
{
    public async Task<MealReviewResult?> EditItemAsync(string userId, Guid mealId, Guid itemId, MealItemEditCommand command, CancellationToken ct) { var meal = await Draft(userId, mealId, ct); if (meal is null) return null; var item = meal.Items.SingleOrDefault(x => x.Id == itemId); if (item is null) return null; var previousFood = item.FoodId; var previousGrams = item.EstimatedGrams; var previousUnit = item.EstimatedServingUnit; await Apply(item, userId, command.FoodId ?? item.FoodId ?? throw new ArgumentException("Food selection is required."), command.Grams, command.ServingQuantity, command.ServingUnitCode, command.PreparationMethod, ct); db.UserFoodCorrections.Add(new UserFoodCorrection { UserId = userId, MealId = mealId, MealItemId = item.Id, PredictedFoodId = previousFood, CorrectedFoodId = item.FoodId, PredictedGrams = previousGrams, CorrectedGrams = item.EstimatedGrams, PredictedServingUnit = previousUnit, CorrectedServingUnit = item.EstimatedServingUnit, CorrectionType = "Edited" }); Totals(meal); await db.SaveChangesAsync(ct); return Review(meal); }
    public async Task<MealReviewResult?> AddItemAsync(string userId, Guid mealId, MealItemAddCommand command, CancellationToken ct) { var meal = await Draft(userId, mealId, ct); if (meal is null) return null; var item = new MealItem { MealId = meal.Id, DetectedName = "Manually added", RequiresConfirmation = false, UserConfirmed = true }; await Apply(item, userId, command.FoodId, command.Grams, command.ServingQuantity, command.ServingUnitCode, command.PreparationMethod, ct); meal.Items.Add(item); db.UserFoodCorrections.Add(new UserFoodCorrection { UserId = userId, MealId = mealId, MealItemId = item.Id, CorrectedFoodId = item.FoodId, CorrectedGrams = item.EstimatedGrams, CorrectedServingUnit = item.EstimatedServingUnit, CorrectionType = "Added" }); Totals(meal); await db.SaveChangesAsync(ct); return Review(meal); }
    public async Task<MealReviewResult?> RemoveItemAsync(string userId, Guid mealId, Guid itemId, CancellationToken ct) { var meal = await Draft(userId, mealId, ct); if (meal is null) return null; var item = meal.Items.SingleOrDefault(x => x.Id == itemId); if (item is null) return null; db.UserFoodCorrections.Add(new UserFoodCorrection { UserId = userId, MealId = mealId, MealItemId = item.Id, PredictedFoodId = item.FoodId, PredictedGrams = item.EstimatedGrams, PredictedServingUnit = item.EstimatedServingUnit, CorrectionType = "Removed" }); db.MealItems.Remove(item); meal.Items.Remove(item); Totals(meal); await db.SaveChangesAsync(ct); return Review(meal); }
    public async Task<MealReviewResult?> ConfirmAsync(string userId, Guid mealId, CancellationToken ct) { var meal = await Draft(userId, mealId, ct); if (meal is null) return null; if (meal.Items.Count == 0) throw new ArgumentException("A meal requires at least one item."); meal.Status = MealStatus.Confirmed; foreach (var item in meal.Items) item.UserConfirmed = true; Totals(meal); await db.SaveChangesAsync(ct); await RecalculateSummary(userId, DateOnly.FromDateTime(meal.ConsumedAtUtc), ct); await db.SaveChangesAsync(ct); return Review(meal); }
    public async Task<bool> DeleteAsync(string userId, Guid mealId, CancellationToken ct) { var meal = await db.Meals.SingleOrDefaultAsync(x => x.Id == mealId && x.UserId == userId && x.Status != MealStatus.Deleted, ct); if (meal is null) return false; var date = DateOnly.FromDateTime(meal.ConsumedAtUtc); meal.Status = MealStatus.Deleted; await db.SaveChangesAsync(ct); await RecalculateSummary(userId, date, ct); await db.SaveChangesAsync(ct); return true; }
    public async Task<IReadOnlyList<MealHistoryEntry>> GetHistoryAsync(string userId, DateTime? fromUtc, DateTime? toUtc, int take, CancellationToken ct) { var q = db.Meals.AsNoTracking().Where(x => x.UserId == userId && x.Status == MealStatus.Confirmed); if (fromUtc.HasValue) q = q.Where(x => x.ConsumedAtUtc >= fromUtc); if (toUtc.HasValue) q = q.Where(x => x.ConsumedAtUtc <= toUtc); return await q.OrderByDescending(x => x.ConsumedAtUtc).Take(Math.Clamp(take, 1, 100)).Select(x => new MealHistoryEntry(x.Id, x.Name, x.MealType, x.ConsumedAtUtc, x.Status, x.TotalCalories, x.TotalProteinGrams, x.TotalCarbohydrateGrams, x.TotalFatGrams, x.TotalFibreGrams)).ToListAsync(ct); }
    public async Task<IReadOnlyList<FoodCorrectionHistoryEntry>?> GetCorrectionsAsync(string userId, Guid mealId, CancellationToken ct) { if (!await db.Meals.AsNoTracking().AnyAsync(x => x.Id == mealId && x.UserId == userId, ct)) return null; return await db.UserFoodCorrections.AsNoTracking().Where(x => x.UserId == userId && x.MealId == mealId).OrderBy(x => x.CreatedAtUtc).Select(x => new FoodCorrectionHistoryEntry(x.Id, x.MealItemId, x.PredictedFoodId, x.CorrectedFoodId, x.PredictedGrams, x.CorrectedGrams, x.PredictedServingUnit, x.CorrectedServingUnit, x.CorrectionType, x.CreatedAtUtc)).ToListAsync(ct); }
    public async Task<DailyNutritionSummaryResult> GetSummaryAsync(string userId, DateOnly summaryDate, CancellationToken ct) { var summary = await db.DailyNutritionSummaries.AsNoTracking().SingleOrDefaultAsync(x => x.UserId == userId && x.SummaryDate == summaryDate, ct); return summary is null ? new(summaryDate, 0, 0, 0, 0, 0, 0) : new(summary.SummaryDate, summary.TotalCalories, summary.TotalProteinGrams, summary.TotalCarbohydrateGrams, summary.TotalFatGrams, summary.TotalFibreGrams, summary.MealCount); }
    private async Task<Meal?> Draft(string userId, Guid mealId, CancellationToken ct) => await db.Meals.Include(x => x.Items).Include(x => x.AnalysisRuns).SingleOrDefaultAsync(x => x.Id == mealId && x.UserId == userId && x.Status == MealStatus.AwaitingReview, ct);
    private async Task Apply(MealItem item, string userId, Guid foodId, decimal? grams, decimal? servingQuantity, string? servingCode, PreparationMethod method, CancellationToken ct) { var food = await db.Foods.Include(x => x.ServingConversions).ThenInclude(x => x.ServingUnit).SingleOrDefaultAsync(x => x.Id == foodId && x.IsActive && (!x.IsUserCreated || x.OwnerUserId == userId), ct) ?? throw new ArgumentException("Food was not found."); var resolvedGrams = grams; if (resolvedGrams is null) { var conversion = food.ServingConversions.SingleOrDefault(x => x.IsDefault && x.ServingUnit != null && x.ServingUnit.Code == servingCode) ?? throw new ArgumentException("A valid food-specific serving conversion is required."); if (servingQuantity is null or <= 0) throw new ArgumentException("Serving quantity must be positive."); resolvedGrams = servingQuantity.Value * conversion.EquivalentGrams / conversion.Quantity; } if (resolvedGrams <= 0) throw new ArgumentException("Grams must be positive."); var scaled = nutrition.CalculateForGrams(new(food.CaloriesPer100Grams, food.ProteinGramsPer100Grams, food.CarbohydrateGramsPer100Grams, food.FatGramsPer100Grams, food.FibreGramsPer100Grams, food.SugarGramsPer100Grams, food.SodiumMilligramsPer100Grams), resolvedGrams.Value); item.FoodId = food.Id; item.DetectedName = food.DisplayName; item.CanonicalName = food.CanonicalName; item.PreparationMethod = method; item.EstimatedGrams = scaled.Grams; item.EstimatedQuantity = servingQuantity; item.EstimatedServingUnit = servingCode ?? "gram"; item.Calories = scaled.Calories; item.ProteinGrams = scaled.Protein; item.CarbohydrateGrams = scaled.Carbohydrates; item.FatGrams = scaled.Fat; item.FibreGrams = scaled.Fibre; item.NutritionMatchConfidence = 1; item.RequiresConfirmation = false; item.UserConfirmed = true; item.Warnings = null; }
    private async Task RecalculateSummary(string userId, DateOnly date, CancellationToken ct) { var start = date.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc); var end = start.AddDays(1); var meals = await db.Meals.Where(x => x.UserId == userId && x.Status == MealStatus.Confirmed && x.ConsumedAtUtc >= start && x.ConsumedAtUtc < end).ToListAsync(ct); var summary = await db.DailyNutritionSummaries.SingleOrDefaultAsync(x => x.UserId == userId && x.SummaryDate == date, ct); if (summary is null) { summary = new DailyNutritionSummary { UserId = userId, SummaryDate = date }; db.DailyNutritionSummaries.Add(summary); } summary.TotalCalories = meals.Sum(x => x.TotalCalories); summary.TotalProteinGrams = meals.Sum(x => x.TotalProteinGrams); summary.TotalCarbohydrateGrams = meals.Sum(x => x.TotalCarbohydrateGrams); summary.TotalFatGrams = meals.Sum(x => x.TotalFatGrams); summary.TotalFibreGrams = meals.Sum(x => x.TotalFibreGrams); summary.MealCount = meals.Count; }
    private static void Totals(Meal meal) { meal.TotalCalories = meal.Items.Sum(x => x.Calories); meal.TotalProteinGrams = meal.Items.Sum(x => x.ProteinGrams); meal.TotalCarbohydrateGrams = meal.Items.Sum(x => x.CarbohydrateGrams); meal.TotalFatGrams = meal.Items.Sum(x => x.FatGrams); meal.TotalFibreGrams = meal.Items.Sum(x => x.FibreGrams); }
    private static MealReviewResult Review(Meal meal) { var run = meal.AnalysisRuns.OrderByDescending(x => x.CreatedAtUtc).FirstOrDefault(); var items = meal.Items.Select(x => new MealItemReview(x.Id, x.FoodId, x.DetectedName, x.RegionalName, x.CanonicalName, x.PreparationMethod, x.EstimatedQuantity, x.EstimatedServingUnit, x.EstimatedGrams, x.Calories, x.ProteinGrams, x.CarbohydrateGrams, x.FatGrams, x.FibreGrams, x.RecognitionConfidence, x.PortionConfidence, x.NutritionMatchConfidence, x.RequiresConfirmation, string.IsNullOrWhiteSpace(x.Warnings) ? [] : x.Warnings.Split(" | "))).ToList(); return new(meal.Id, meal.Name, meal.MealType, meal.ConsumedAtUtc, meal.Status, meal.TotalCalories, meal.TotalProteinGrams, meal.TotalCarbohydrateGrams, meal.TotalFatGrams, meal.TotalFibreGrams, meal.OverallConfidence, items, items.SelectMany(x => x.Warnings).Distinct().ToList(), run?.Provider ?? "Manual", run?.PromptVersion ?? "manual", run?.SchemaVersion ?? "manual"); }
}


