// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutritionTracker.Infrastructure.Persistence;

#nullable disable

namespace NutritionTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NutritionTrackerDbContext))]
    partial class NutritionTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutritionTracker.Domain.Authentication.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("application_users", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Authentication.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key", "Operation")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CaloriesPer100Grams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("CarbohydrateGramsPer100Grams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("FatGramsPer100Grams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("FibreGramsPer100Grams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("FoodState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreparationMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("ProteinGramsPer100Grams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal?>("SodiumMilligramsPer100Grams")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("SugarGramsPer100Grams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Cuisine");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsVerified");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("foods", null, t =>
                        {
                            t.HasCheckConstraint("CK_foods_nutrients_nonnegative", "\"CaloriesPer100Grams\" >= 0 AND \"ProteinGramsPer100Grams\" BETWEEN 0 AND 100 AND \"CarbohydrateGramsPer100Grams\" BETWEEN 0 AND 100 AND \"FatGramsPer100Grams\" BETWEEN 0 AND 100 AND \"FibreGramsPer100Grams\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("AliasType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Transliteration")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAlias");

                    b.HasIndex("FoodId", "NormalizedAlias")
                        .IsUnique();

                    b.ToTable("food_aliases", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodNutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NutrientDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValuePer100Grams")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NutrientDefinitionId");

                    b.HasIndex("FoodId", "NutrientDefinitionId")
                        .IsUnique();

                    b.ToTable("food_nutrients", null, t =>
                        {
                            t.HasCheckConstraint("CK_food_nutrients_nonnegative", "\"ValuePer100Grams\" >= 0");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodServingConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EquivalentGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<Guid>("ServingUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServingUnitId");

                    b.HasIndex("FoodId", "ServingUnitId")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.ToTable("food_serving_conversions", null, t =>
                        {
                            t.HasCheckConstraint("CK_food_serving_conversions_positive", "\"Quantity\" > 0 AND \"EquivalentGrams\" > 0");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("food_tags", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodTagAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodTagId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FoodTagId");

                    b.HasIndex("FoodId", "FoodTagId")
                        .IsUnique();

                    b.ToTable("food_tag_assignments", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.NutrientDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCore")
                        .HasColumnType("boolean");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("nutrient_definitions", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSavedTemplate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PreparationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("ServingCount")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal>("YieldGrams")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("recipes", null, t =>
                        {
                            t.HasCheckConstraint("CK_recipes_yield", "\"YieldGrams\" > 0 AND \"ServingCount\" > 0");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Grams")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("RecipeId", "FoodId");

                    b.ToTable("recipe_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_recipe_ingredients_grams", "\"Grams\" > 0");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.ServingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCountBased")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMetric")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("serving_units", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.AiAnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FailureType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InputImageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId", "InputImageHash");

                    b.ToTable("ai_analysis_runs", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.DailyNutritionSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MealCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalCalories")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("TotalCarbohydrateGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("TotalFatGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("TotalFibreGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("TotalProteinGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SummaryDate")
                        .IsUnique();

                    b.ToTable("daily_nutrition_summaries", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Name")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("OverallConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalCalories")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("TotalCarbohydrateGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("TotalFatGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("TotalFibreGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("TotalProteinGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "ConsumedAtUtc");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.MealImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("MealId", "Sha256Hash");

                    b.ToTable("meal_images", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Calories")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("CanonicalName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("CarbohydrateGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal?>("EstimatedGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal?>("EstimatedQuantity")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("EstimatedServingUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("FatGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("FibreGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<Guid?>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NutritionMatchConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("PortionConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("PreparationMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("ProteinGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("RecognitionConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("RegionalName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("RequiresConfirmation")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UserConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Warnings")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("meal_items", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.UserFoodCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrectedFoodId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CorrectedGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("CorrectedServingUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CorrectionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PredictedFoodId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PredictedGrams")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("PredictedServingUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("user_food_corrections", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.DailyNutritionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasalMetabolicRate")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CalculationWarnings")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("CarbohydrateGrams")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FatGrams")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("FibreGrams")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("ProteinGrams")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("TargetCalories")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("TotalDailyEnergyExpenditure")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "EffectiveDate");

                    b.ToTable("daily_nutrition_targets", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.FastingWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOperationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientOperationId")
                        .IsUnique()
                        .HasFilter("\"ClientOperationId\" IS NOT NULL");

                    b.HasIndex("UserId", "StartedAtUtc");

                    b.ToTable("fasting_windows", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.HydrationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOperationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Millilitres")
                        .HasPrecision(8, 1)
                        .HasColumnType("numeric(8,1)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientOperationId")
                        .IsUnique()
                        .HasFilter("\"ClientOperationId\" IS NOT NULL");

                    b.HasIndex("UserId", "RecordedAtUtc");

                    b.ToTable("hydration_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_hydration_entries_amount", "\"Millilitres\" > 0");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.ReminderPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOperationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("LocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Type");

                    b.ToTable("reminder_preferences", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.UserDietaryPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Code")
                        .IsUnique();

                    b.ToTable("user_dietary_preferences", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DietPreference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsOnboardingComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PreferredMeasurementSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("TargetWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.WeightEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "RecordedAtUtc");

                    b.ToTable("weight_entries", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Authentication.RefreshToken", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Authentication.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodAlias", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.Food", "Food")
                        .WithMany("Aliases")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodNutrient", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.Food", "Food")
                        .WithMany("Nutrients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Foods.NutrientDefinition", "NutrientDefinition")
                        .WithMany()
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("NutrientDefinition");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodServingConversion", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.Food", "Food")
                        .WithMany("ServingConversions")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Foods.ServingUnit", "ServingUnit")
                        .WithMany("FoodServingConversions")
                        .HasForeignKey("ServingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("ServingUnit");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodTagAssignment", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.Food", "Food")
                        .WithMany("TagAssignments")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Foods.FoodTag", "FoodTag")
                        .WithMany()
                        .HasForeignKey("FoodTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("FoodTag");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.RecipeIngredient", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Foods.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.AiAnalysisRun", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Meals.Meal", "Meal")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.MealImage", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Meals.Meal", "Meal")
                        .WithMany("Images")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.MealItem", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NutritionTracker.Domain.Meals.Meal", "Meal")
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.UserFoodCorrection", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Meals.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.DailyNutritionTarget", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Profiles.UserProfile", "UserProfile")
                        .WithMany("NutritionTargets")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.WeightEntry", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Profiles.UserProfile", "UserProfile")
                        .WithMany("WeightEntries")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.Food", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Nutrients");

                    b.Navigation("ServingConversions");

                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.ServingUnit", b =>
                {
                    b.Navigation("FoodServingConversions");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.Meal", b =>
                {
                    b.Navigation("AnalysisRuns");

                    b.Navigation("Images");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Profiles.UserProfile", b =>
                {
                    b.Navigation("NutritionTargets");

                    b.Navigation("WeightEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
