using NutritionTracker.Domain.Foods;
using NutritionTracker.Domain.Meals;
using NutritionTracker.Application.Foods;
namespace NutritionTracker.Application.Meals;

public sealed record MealAnalysisCommand(string UserId, byte[] ImageBytes, string MimeType, string? FileName, DateTime ConsumedAtUtc, string Locale, IReadOnlyList<string> CuisineHints, string? MockScenario, string? CorrelationId, string? ProviderId = null, string? ModelId = null);
public sealed record FoodMatchResult(Guid FoodId, string CanonicalName, FoodNutritionValues Nutrition, decimal Confidence);
public sealed record FoodResolutionSuggestion(Guid FoodId, string DisplayName, string CanonicalName, FoodNutritionValues NutritionPer100Grams, decimal Confidence, string Rationale, bool IsVerified, bool IsUserCreated);
public enum FoodResolutionMode { CatalogMatch, NutritionEstimate }
public sealed record FoodNutritionEstimate(string Name, string? Description, FoodCategory Category, Cuisine Cuisine, PreparationMethod PreparationMethod, FoodState FoodState, FoodNutritionValues NutritionPer100Grams, decimal Confidence, IReadOnlyList<string> Assumptions, string Warning, string EstimateToken);
public sealed record FoodResolutionResult(Guid MealId, Guid MealItemId, string DetectedName, string Query, IReadOnlyList<FoodResolutionSuggestion> Suggestions, string? NoMatchReason, FoodNutritionEstimate? Estimate, string Provider, string? Model);
public sealed record FoodResolutionCommand(string? Query = null, FoodResolutionMode Mode = FoodResolutionMode.CatalogMatch, string? ProviderId = null, string? ModelId = null);
public sealed record ConfirmFoodEstimateCommand(string EstimateToken, string Name, string? Description, FoodCategory Category, Cuisine Cuisine, PreparationMethod PreparationMethod, FoodState FoodState, FoodNutritionValues NutritionPer100Grams, decimal Grams);
public sealed record MealItemReview(Guid Id, Guid? FoodId, string DetectedName, string? RegionalName, string? CanonicalName, PreparationMethod PreparationMethod, decimal? EstimatedQuantity, string EstimatedServingUnit, decimal? EstimatedGrams, decimal? Calories, decimal? ProteinGrams, decimal? CarbohydrateGrams, decimal? FatGrams, decimal? FibreGrams, decimal RecognitionConfidence, decimal PortionConfidence, decimal NutritionMatchConfidence, NutritionMatchState NutritionMatchState, bool RequiresConfirmation, IReadOnlyList<string> Warnings);
public sealed record MealReviewResult(Guid MealId, string? Name, MealType MealType, DateTime ConsumedAtUtc, MealStatus Status, decimal TotalCalories, decimal TotalProteinGrams, decimal TotalCarbohydrateGrams, decimal TotalFatGrams, decimal TotalFibreGrams, bool HasIncompleteNutrition, decimal OverallConfidence, IReadOnlyList<MealItemReview> Items, IReadOnlyList<string> Warnings, string Provider, string? Model, string PromptVersion, string SchemaVersion, bool HasImage);
public interface IMealAnalysisPipeline { Task<MealReviewResult> AnalyseAsync(MealAnalysisCommand command, CancellationToken ct); Task<MealReviewResult?> GetReviewAsync(string userId, Guid mealId, CancellationToken ct); }
public interface IMealImageStorage { Task<string> SaveAsync(ReadOnlyMemory<byte> image, string mimeType, string userId, Guid mealId, CancellationToken ct); Task<byte[]?> ReadAsync(string storageKey, CancellationToken ct); Task DeleteAsync(string storageKey, CancellationToken ct); }
public interface IFoodMatcher { Task<FoodMatchResult?> MatchAsync(string userId, string detectedName, string? regionalName, IReadOnlyList<string>? alternatives, CancellationToken ct); }
public interface IFoodResolutionAssistant { Task<FoodResolutionResult?> SuggestAsync(string userId, Guid mealId, Guid mealItemId, FoodResolutionCommand command, CancellationToken ct); Task<MealReviewResult?> ConfirmEstimateAsync(string userId, Guid mealId, Guid mealItemId, ConfirmFoodEstimateCommand command, CancellationToken ct); }
public sealed record MealItemEditCommand(Guid? FoodId, decimal? Grams, decimal? ServingQuantity, string? ServingUnitCode, PreparationMethod PreparationMethod);
public sealed record MealItemAddCommand(Guid FoodId, decimal? Grams, decimal? ServingQuantity, string? ServingUnitCode, PreparationMethod PreparationMethod);
public sealed record ManualMealItemCommand(Guid FoodId, decimal Grams, PreparationMethod PreparationMethod);
public sealed record ManualMealCommand(string? Name, MealType MealType, DateTime ConsumedAtUtc, IReadOnlyList<ManualMealItemCommand> Items);
public sealed record DailyNutritionSummaryResult(DateOnly SummaryDate, decimal TotalCalories, decimal TotalProteinGrams, decimal TotalCarbohydrateGrams, decimal TotalFatGrams, decimal TotalFibreGrams, int MealCount);
public sealed record MealHistoryEntry(Guid Id, string? Name, MealType MealType, DateTime ConsumedAtUtc, MealStatus Status, decimal TotalCalories, decimal TotalProteinGrams, decimal TotalCarbohydrateGrams, decimal TotalFatGrams, decimal TotalFibreGrams, bool HasImage);
public sealed record MealActivityDay(DateOnly Date, DateTime StartUtc, DateTime EndUtc, int MealCount, decimal Calories, decimal? TargetCalories, decimal? AdherencePercent);
public sealed record MealActivityResult(DateOnly FromDate, DateOnly ToDate, string Timezone, IReadOnlyList<MealActivityDay> Days);
public sealed record FoodCorrectionHistoryEntry(Guid Id, Guid? MealItemId, Guid? PredictedFoodId, Guid? CorrectedFoodId, decimal? PredictedGrams, decimal? CorrectedGrams, string? PredictedServingUnit, string? CorrectedServingUnit, string CorrectionType, DateTime CreatedAtUtc);
public interface IMealManagementService { Task<MealReviewResult> CreateManualAsync(string userId, ManualMealCommand command, CancellationToken ct); Task<MealReviewResult?> EditItemAsync(string userId, Guid mealId, Guid itemId, MealItemEditCommand command, CancellationToken ct); Task<MealReviewResult?> ApplyEstimatedFoodAsync(string userId, Guid mealId, Guid itemId, ConfirmFoodEstimateCommand command, string provider, string? model, CancellationToken ct); Task<MealReviewResult?> AddItemAsync(string userId, Guid mealId, MealItemAddCommand command, CancellationToken ct); Task<MealReviewResult?> RemoveItemAsync(string userId, Guid mealId, Guid itemId, CancellationToken ct); Task<MealReviewResult?> ConfirmAsync(string userId, Guid mealId, CancellationToken ct); Task<bool> DeleteAsync(string userId, Guid mealId, CancellationToken ct); Task<IReadOnlyList<MealHistoryEntry>> GetHistoryAsync(string userId, DateTime? fromUtc, DateTime? toUtc, int take, CancellationToken ct); Task<MealActivityResult> GetActivityAsync(string userId, DateOnly fromDate, DateOnly toDate, CancellationToken ct); Task<IReadOnlyList<FoodCorrectionHistoryEntry>?> GetCorrectionsAsync(string userId, Guid mealId, CancellationToken ct); Task<DailyNutritionSummaryResult> GetSummaryAsync(string userId, DateOnly summaryDate, CancellationToken ct); }
