using Microsoft.EntityFrameworkCore;
using NutritionTracker.Application.Foods;
using NutritionTracker.Domain.Foods;
using NutritionTracker.Infrastructure.Persistence;

namespace NutritionTracker.Infrastructure.Foods;

public sealed class FoodService(NutritionTrackerDbContext db, IFoodNameNormalizer normalizer, IFoodNutritionCalculator calculator) : IFoodService
{
    public async Task<IReadOnlyList<FoodSummary>> SearchAsync(string userId, string query, FoodCategory? category, Cuisine? cuisine, PreparationMethod? preparation, bool verifiedOnly, bool includeUserFoods, int limit, CancellationToken ct) { var q = normalizer.Normalize(query); var foods = db.Foods.AsNoTracking().Where(x => x.IsActive && (!x.IsUserCreated || includeUserFoods && x.OwnerUserId == userId) && (!verifiedOnly || x.IsVerified) && (x.NormalizedName.Contains(q) || x.Aliases.Any(a => a.NormalizedAlias.Contains(q)))); if (category.HasValue) foods = foods.Where(x => x.Category == category); if (cuisine.HasValue) foods = foods.Where(x => x.Cuisine == cuisine); if (preparation.HasValue) foods = foods.Where(x => x.PreparationMethod == preparation); var rows = await foods.OrderBy(x => x.NormalizedName).Include(x => x.Aliases).Include(x => x.ServingConversions).ThenInclude(x => x.ServingUnit).AsSplitQuery().Take(Math.Clamp(limit, 1, 50)).ToListAsync(ct); return rows.Select(x => Summary(x, q)).OrderBy(x => x.MatchType).ThenByDescending(x => x.IsVerified).ThenBy(x => x.DisplayName).ToList(); }
    public async Task<FoodDetails?> GetAsync(string userId, Guid id, CancellationToken ct) { var x = await Visible(userId).AsNoTracking().Include(f => f.Aliases).Include(f => f.ServingConversions).ThenInclude(c => c.ServingUnit).SingleOrDefaultAsync(f => f.Id == id, ct); return x is null ? null : new(x.Id, x.CanonicalName, x.DisplayName, x.Description, x.Category, x.Cuisine, x.PreparationMethod, x.FoodState, Values(x), x.Aliases.OrderByDescending(a => a.Priority).Select(a => a.Alias).ToList(), x.ServingConversions.Select(c => new ServingConversionResult(c.ServingUnit.Code, c.Quantity, c.EquivalentGrams, c.Source, c.Confidence)).ToList(), x.DataSource, x.SourceReference, x.SourceVersion, x.IsVerified, x.IsUserCreated, IsEstimate(x)); }
    public async Task<ScaledNutritionResult?> CalculateGramsAsync(string userId, Guid id, decimal grams, CancellationToken ct) { var x = await Visible(userId).AsNoTracking().SingleOrDefaultAsync(f => f.Id == id, ct); return x is null ? null : calculator.CalculateForGrams(Values(x), grams); }
    public async Task<ScaledNutritionResult?> CalculateServingAsync(string userId, Guid id, string code, decimal quantity, CancellationToken ct) { var x = await Visible(userId).AsNoTracking().Include(f => f.ServingConversions).ThenInclude(c => c.ServingUnit).SingleOrDefaultAsync(f => f.Id == id, ct); var c = x?.ServingConversions.SingleOrDefault(c => c.ServingUnit.Code == code && c.IsDefault); return x is null || c is null ? null : calculator.CalculateForServing(Values(x), new(c.Quantity, c.EquivalentGrams, c.Source, c.Confidence), quantity); }
    public async Task<FoodDetails> CreateCustomAsync(string userId, CustomFoodCommand command, CancellationToken ct) { var normalized = normalizer.Normalize(command.CanonicalName ?? command.DisplayName); if (await db.Foods.AnyAsync(x => x.OwnerUserId == userId && x.NormalizedName == normalized && x.IsActive, ct)) throw new InvalidOperationException("Duplicate custom food."); var food = Apply(new Food { OwnerUserId = userId, IsUserCreated = true, IsVerified = false, IsActive = true, DataSource = "User supplied" }, command, normalized); db.Foods.Add(food); await db.SaveChangesAsync(ct); return (await GetAsync(userId, food.Id, ct))!; }
    public async Task<FoodDetails?> UpdateCustomAsync(string userId, Guid id, CustomFoodCommand command, CancellationToken ct) { var food = await db.Foods.Include(x => x.Aliases).SingleOrDefaultAsync(x => x.Id == id && x.IsUserCreated && x.OwnerUserId == userId && x.IsActive, ct); if (food is null) return null; Apply(food, command, normalizer.Normalize(command.CanonicalName ?? command.DisplayName)); await db.SaveChangesAsync(ct); return await GetAsync(userId, id, ct); }
    public async Task<bool> DeactivateCustomAsync(string userId, Guid id, CancellationToken ct) { var food = await db.Foods.SingleOrDefaultAsync(x => x.Id == id && x.IsUserCreated && x.OwnerUserId == userId && x.IsActive, ct); if (food is null) return false; food.IsActive = false; await db.SaveChangesAsync(ct); return true; }
    private IQueryable<Food> Visible(string userId) => db.Foods.Where(x => x.IsActive && (!x.IsUserCreated || x.OwnerUserId == userId));
    private static FoodNutritionValues Values(Food x) => new(x.CaloriesPer100Grams, x.ProteinGramsPer100Grams, x.CarbohydrateGramsPer100Grams, x.FatGramsPer100Grams, x.FibreGramsPer100Grams, x.SugarGramsPer100Grams, x.SodiumMilligramsPer100Grams);
    private Food Apply(Food food, CustomFoodCommand command, string normalized) { _ = calculator.CalculateForGrams(command.NutritionPer100Grams, 100); food.CanonicalName = (command.CanonicalName ?? command.DisplayName).Trim(); food.NormalizedName = normalized; food.DisplayName = command.DisplayName.Trim(); food.Description = command.Description?.Trim(); food.Category = command.Category; food.Cuisine = command.Cuisine; food.PreparationMethod = command.PreparationMethod; food.FoodState = command.FoodState; food.CaloriesPer100Grams = command.NutritionPer100Grams.Calories; food.ProteinGramsPer100Grams = command.NutritionPer100Grams.Protein; food.CarbohydrateGramsPer100Grams = command.NutritionPer100Grams.Carbohydrates; food.FatGramsPer100Grams = command.NutritionPer100Grams.Fat; food.FibreGramsPer100Grams = command.NutritionPer100Grams.Fibre; food.SugarGramsPer100Grams = command.NutritionPer100Grams.Sugar; food.SodiumMilligramsPer100Grams = command.NutritionPer100Grams.SodiumMilligrams; food.Aliases.Clear(); foreach (var alias in command.Aliases.Distinct(StringComparer.OrdinalIgnoreCase)) food.Aliases.Add(new FoodAlias { Alias = alias.Trim(), NormalizedAlias = normalizer.Normalize(alias), AliasType = AliasType.CommonName }); return food; }
    private static FoodSummary Summary(Food x, string q) { var exactAlias = x.Aliases.Any(a => a.NormalizedAlias == q); var prefixAlias = x.Aliases.Any(a => a.NormalizedAlias.StartsWith(q, StringComparison.Ordinal)); var type = x.IsUserCreated ? FoodMatchType.UserCustom : x.NormalizedName == q ? FoodMatchType.ExactCanonical : exactAlias ? FoodMatchType.ExactAlias : x.NormalizedName.StartsWith(q, StringComparison.Ordinal) ? FoodMatchType.CanonicalPrefix : prefixAlias ? FoodMatchType.AliasPrefix : x.NormalizedName.Contains(q) ? FoodMatchType.CanonicalContains : FoodMatchType.AliasContains; return new(x.Id, x.DisplayName, x.CanonicalName, x.Aliases.Where(a => a.AliasType == AliasType.RegionalName).OrderByDescending(a => a.Priority).Select(a => a.Alias).FirstOrDefault(), x.Category, x.Cuisine, x.PreparationMethod, x.FoodState, Values(x), x.IsVerified, x.IsUserCreated, IsEstimate(x), type, x.ServingConversions.Select(c => c.ServingUnit.Code).Distinct().ToList()); }
    private static bool IsEstimate(Food x) => x.DataSource.StartsWith("AI estimate", StringComparison.OrdinalIgnoreCase);
}
