using FluentValidation;
using NutritionTracker.Application.Nutrition;
using NutritionTracker.Application.Profiles;
using NutritionTracker.Domain.Profiles;

namespace NutritionTracker.Api.Profiles;

public sealed record ProfileRequest(string Name, DateOnly DateOfBirth, BiologicalSex BiologicalSex, decimal HeightCm, decimal CurrentWeightKg, decimal TargetWeightKg, ActivityLevel ActivityLevel, GoalType GoalType, DietPreference DietPreference, PreferredMeasurementSystem PreferredMeasurementSystem, string Timezone, decimal? CustomCalories, decimal? CustomProteinGrams, decimal? CustomCarbohydrateGrams, decimal? CustomFatGrams);
public sealed record WeightRequest(decimal WeightKg, DateTime RecordedAtUtc, string? Notes);
public sealed class ProfileRequestValidator : AbstractValidator<ProfileRequest> { public ProfileRequestValidator() { RuleFor(x => x.Name).NotEmpty().MaximumLength(120).Must(x => x == x.Trim()); RuleFor(x => x.HeightCm).InclusiveBetween(100, 250); RuleFor(x => x.CurrentWeightKg).InclusiveBetween(25, 400); RuleFor(x => x.TargetWeightKg).InclusiveBetween(25, 400); RuleFor(x => x.DateOfBirth).LessThan(DateOnly.FromDateTime(DateTime.UtcNow)); RuleFor(x => x.Timezone).NotEmpty().Must(IsTimeZone).WithMessage("Timezone must be a valid IANA or Windows timezone."); RuleFor(x => x).Must(x => x.GoalType != GoalType.LoseWeightSlowly && x.GoalType != GoalType.LoseWeightModerately || x.TargetWeightKg < x.CurrentWeightKg).WithMessage("Weight-loss goals require a lower target weight."); RuleFor(x => x).Must(x => x.GoalType != GoalType.GainWeightSlowly && x.GoalType != GoalType.GainMuscle || x.TargetWeightKg > x.CurrentWeightKg).WithMessage("Weight-gain goals require a higher target weight."); RuleFor(x => x.CustomCalories).NotNull().GreaterThan(0).When(x => x.GoalType == GoalType.Custom); RuleFor(x => x.CustomProteinGrams).NotNull().GreaterThanOrEqualTo(0).When(x => x.GoalType == GoalType.Custom); RuleFor(x => x.CustomCarbohydrateGrams).NotNull().GreaterThanOrEqualTo(0).When(x => x.GoalType == GoalType.Custom); RuleFor(x => x.CustomFatGrams).NotNull().GreaterThanOrEqualTo(0).When(x => x.GoalType == GoalType.Custom); } private static bool IsTimeZone(string x) { try { _ = TimeZoneInfo.FindSystemTimeZoneById(x); return true; } catch (TimeZoneNotFoundException) { return false; } } }
public sealed class WeightRequestValidator : AbstractValidator<WeightRequest> { public WeightRequestValidator() { RuleFor(x => x.WeightKg).InclusiveBetween(25, 400); RuleFor(x => x.RecordedAtUtc).LessThanOrEqualTo(DateTime.UtcNow).Must(x => x.Kind == DateTimeKind.Utc).WithMessage("RecordedAtUtc must be UTC."); RuleFor(x => x.Notes).MaximumLength(500); } }
public static class ProfileEndpoints
{
    public static IEndpointRouteBuilder MapProfileEndpoints(this IEndpointRouteBuilder routes)
    { var p = routes.MapGroup("/api/profile"); p.MapPost("", Create); p.MapGet("", Get); p.MapPut("", Update); p.MapPost("/recalculate-targets", Recalculate); var w = routes.MapGroup("/api/weight"); w.MapPost("", AddWeight); w.MapGet("", GetWeights); return routes; }
    private static async Task<IResult> Create(ProfileRequest r, HttpContext c, IProfileService s, CancellationToken ct) { try { var x = await s.CreateAsync(User(c), ToCommand(r), ct); return Results.Created("/api/profile", x); } catch (InvalidOperationException) { return Results.Conflict(); } catch (NutritionCalculationException e) { return Results.UnprocessableEntity(new { title = e.Message }); } }
    private static async Task<IResult> Get(HttpContext c, IProfileService s, CancellationToken ct) => await s.GetAsync(User(c), ct) is { } x ? Results.Ok(x) : Results.NotFound();
    private static async Task<IResult> Update(ProfileRequest r, HttpContext c, IProfileService s, CancellationToken ct) { try { return await s.UpdateAsync(User(c), ToCommand(r), ct) is { } x ? Results.Ok(x) : Results.NotFound(); } catch (NutritionCalculationException e) { return Results.UnprocessableEntity(new { title = e.Message }); } }
    private static async Task<IResult> Recalculate(HttpContext c, IProfileService s, CancellationToken ct) { try { return await s.RecalculateAsync(User(c), ct) is { } x ? Results.Ok(x) : Results.NotFound(); } catch (NutritionCalculationException e) { return Results.UnprocessableEntity(new { title = e.Message }); } }
    private static async Task<IResult> AddWeight(WeightRequest r, HttpContext c, IProfileService s, CancellationToken ct) => await s.AddWeightAsync(User(c), new(r.WeightKg, r.RecordedAtUtc, r.Notes), ct) is { } x ? Results.Created("/api/weight", x) : Results.NotFound();
    private static async Task<IResult> GetWeights(HttpContext c, IProfileService s, DateTime? fromUtc, DateTime? toUtc, bool descending = true, int take = 100, CancellationToken ct = default) => Results.Ok(await s.GetWeightsAsync(User(c), fromUtc, toUtc, descending, Math.Clamp(take, 1, 365), ct));
    private static string User(HttpContext c) => c.Request.Headers.TryGetValue("X-Development-User-Id", out var x) && !string.IsNullOrWhiteSpace(x) ? x.ToString() : throw new BadHttpRequestException("X-Development-User-Id is required.", StatusCodes.Status401Unauthorized);
    private static ProfileCommand ToCommand(ProfileRequest x) => new(x.Name, x.DateOfBirth, x.BiologicalSex, x.HeightCm, x.CurrentWeightKg, x.TargetWeightKg, x.ActivityLevel, x.GoalType, x.DietPreference, x.PreferredMeasurementSystem, x.Timezone, x.CustomCalories, x.CustomProteinGrams, x.CustomCarbohydrateGrams, x.CustomFatGrams);
}
